# SSA PIC 16A Midterm Review - Winter 2023
Topics in today's review notebook (doesn't include everything on the midterm):
1. Mutable and Immutable objects (Python variables)
2. Containers in Python (lists, strings, tuples, sets, dicts)
3. List comprehensions
4. Lambda functions
5. Functions and scope
6. Numpy broadcasting
7. Iterators and Generators

### 1. Mutable and Immutable Objects

An object whose internal state can be changed is mutable. On the other hand, immutable doesn’t allow any change in the object once it has been created. Both of these states are integral to Python data structure. 

Mutable is when something is changeable or has the ability to change. In Python, ‘mutability’ is the ability of objects to change their values. These are often the objects that store a collection of data. Mutable objects are:
* Lists
* Dictionaries
* Sets
* User-defined classes

Immutable is when no change is possible over time. In Python, if the value of an object cannot be changed over time, then it is known as immutable. Once created, the value of these objects is permanent. Immutable objects are:
* Numeric literals (int/float/complex)
* Strings
* Tuples
* Boolean
* Frozen sets

Mutable and immutable objects are handled differently in python. Immutable objects are quicker to access and are expensive to change because it involves the creation of a copy. Whereas mutable objects are easy to change. Use of mutable objects is recommended when there is a need to change the size or content of the object.

### 2. Containers in Python

#### Strings
* Strings are sequences of characters.
* Strings are immutable.
* Strings are created using single or double quotes.
* Strings can be concatenated using + operator.
* Strings can be sliced using the : operator.
* Strings can be indexed using the [] operator.
* Strings can be split into a list of words using the `split()` method.
* Strings can be converted to upper or lower case using the `upper()` or `lower()` methods.

In [62]:
name = "Jonathan Smith"
print(name)
print(name[0:4]) #[start:(stop-1)] [0:n] --> [0 to n-1]
print(name[:10]) #[0:(stop-1)]
#name[3] = 'i' #This will cause an error
print(name[::-1]) #Reverse the string
print(name[-1::-1]) #Reverse the string
print(name[::2]) #Print every other character
print("This won't work:",name[0:14:-1]) #Range is in the wrong direction
first = name.split()[0]
last = name.split()[1]
print(first)
print(last)
print(first+"--"+last) #string concatenation
words = name.split("t") #if no parameter is specified, space is default parameter
print(words)

Jonathan Smith
Jona
Jonathan S
htimS nahtanoJ
htimS nahtanoJ
Jnta mt
This won't work: 
Jonathan
Smith
Jonathan--Smith
['Jona', 'han Smi', 'h']


#### Lists
* Lists are a collection of items in a particular order. 
* They are denoted by square brackets. 
* The items in the list can be of any type and can be duplicates. 
* They are separated by commas and can be empty. 
* They are mutable.

In [ ]:
ll = [1,2,3,4,5,3,4,5]
print(ll)
ll[0] = 10
print(ll)
ll.append(6) #similar to vector.push_back() in C++
ll.append(4)
ll.append(3)
print(ll)
# Showing mutability of lists
list1 = [1,2,3,4,5]
list2 = list1
list3 = [1,2,3,4,5]
print(list1==list2)
print(list1==list3)
print(id(list1), id(list2), id(list3))
list1[0] = 10
list2[1] = 20
print(list1, list2, list3)
print(id(list1), id(list2), id(list3))

[1, 2, 3, 4, 5, 3, 4, 5]
[10, 2, 3, 4, 5, 3, 4, 5]
[10, 2, 3, 4, 5, 3, 4, 5, 6, 4, 3]
True
True
140296190406464 140296190406464 140296190303616
[10, 20, 3, 4, 5] [10, 20, 3, 4, 5] [1, 2, 3, 4, 5]
140296190406464 140296190406464 140296190303616


In [97]:
L0 = [0,1,2]
L = L0
print(L0, id(L0), L, id(L))
print(L0 is L)
L = L + [3,4,5] #This creates a new list and assigns it to L (__add__() magic method for lists class)
print(L0, id(L0), L, id(L))
print(L0 is L)

[0, 1, 2] 140324516788416 [0, 1, 2] 140324516788416
True
[0, 1, 2] 140324516788416 [0, 1, 2, 3, 4, 5] 140324783358976
False


In [89]:
L0 = [0,1,2]
L = L0
print(L0, id(L0), L, id(L))
print(L0 is L)
L.append(3) # This is different from L = L + [3]
L.append(4)
L.append(5) # This is different from L = L + [5]
print(L0, id(L0), L, id(L))
print(L0 is L)

[0, 1, 2] 140324509058112 [0, 1, 2] 140324509058112
True
[0, 1, 2, 3, 4, 5] 140324509058112 [0, 1, 2, 3, 4, 5] 140324509058112
True


In [90]:
L0 = [0,1,2]
L = L0
print(L0, id(L0), L, id(L))
print(L0 is L)
L += [3,4,5] #This is different from L = L + [3,4,5] (__iadd__() magic method for lists class)
print(L0, id(L0), L, id(L))
print(L0 is L)

[0, 1, 2] 140324516692608 [0, 1, 2] 140324516692608
True
[0, 1, 2, 3, 4, 5] 140324516692608 [0, 1, 2, 3, 4, 5] 140324516692608
True


#### Sets
* Sets are a collection of items in no particular order. 
* They are denoted by curly brackets.
* They are unordered and unindexed.
* They cannot contain duplicate items.
* They are mutable.

In [28]:
ll = [1,2,3,4,5,3,4,5,6,4,3]
ss = {1,2,3,3,4,4,5,5}
print(ss)
ss.add(10)
print(ss)
ss.remove(3)
print(ss)
#Lists can be converted to sets
ss2 = set(ll) #All duplicates are removed
ll = list(ss2)
print('Unique elements of ll:',ll)

{1, 2, 3, 4, 5}
{1, 2, 3, 4, 5, 10}
{1, 2, 4, 5, 10}
Unique elements of ll: [1, 2, 3, 4, 5, 6]


* The `frozenset()` function returns an immutable frozenset object initialized with elements from the given iterable.
* Frozen set is just an immutable version of a Python set object. While elements of a set can be modified at any time, elements of the frozen set remain the same after creation.
* Due to this, frozen sets can be used as keys in Dictionary or as elements of another set. But like sets, it is not ordered (the elements can be set at any index).
* The syntax of `frozenset()` function is: `frozenset([iterable])`

#### Tuples
* Tuples are used to store multiple items in a single variable
* Tuples are used to store data that is ordered (indexed) and not changing
* Tuples are immutable and allow duplicate values
* Tuples are created with parentheses `()`
* Tuples are created with a comma separated list of items
* The length of a tuple can be known with the `len()` function

In [43]:
tup = (1,2,3,4,5,3,4,5)
print(tup)
print(tup[0])
#tup[2] = 10 # This will throw an error
print(len(tup))

(1, 2, 3, 4, 5, 3, 4, 5)
1
8


#### Dictionaries
* Dictionaries are used to store data in key:value pairs
* Dictionaries are created with curly braces `{}`
* Dictionaries are created with a comma separated list of key:value pairs
* The length of a dictionary can be known with the `len()` function
* The keys of a dictionary can be accessed with the `keys()` function
* The values of a dictionary can be accessed with the `values()` function
* The items of a dictionary can be accessed with the `items()` function
* The `get()` function can be used to retrieve a value from a dictionary
* They are mutable and allow duplicate values but keys must be unique

In [44]:
dd = {'a':1,'b':2,'c':3, 'd':3, 'e':4}
print(dd['a'])
print(dd['b'])
print(dd.items())
print(dd.keys())
print(dd.values())
print(dd.get('a'))
print(dd.get('f')) # This will return None
print(dd.get('f', 0)) # This will return 0 (default value)
dd['f'] = 10 # This will add a new key-value pair
print(dd)

1
2
dict_items([('a', 1), ('b', 2), ('c', 3), ('d', 3), ('e', 4)])
dict_keys(['a', 'b', 'c', 'd', 'e'])
dict_values([1, 2, 3, 3, 4])
1
None
0
{'a': 1, 'b': 2, 'c': 3, 'd': 3, 'e': 4, 'f': 10}


### 3. List Comprehensions

List comprehensions are fancy-python syntax used for creating lists from iterables like tuples, strings, arrays, lists, etc. 

Syntax: `newList = [expression(element) for element in oldList if condition]`

**Advantages of List Comprehension**
* More time-efficient and space-efficient than loops.
* Require fewer lines of code.
* Transforms iterative statement into a formula.

**Variations of list comprehensions**
1. Basic list comprehension
2. List comprehension with if statement
3. List comprehension using nested for loops
4. List comprehension for working with list of lists using nested for loops

In [98]:
# Basic list comprehension
L1 = []
for x in range(10):
    L1.append(x**2)
print(L1)

L = [x**2 for x in range(10)]
print(L)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [47]:
# List comprehension with if statement
L1 = []
for x in range(20):
    if x%2 == 0:
        L1.append(x**2)
print(L1)

L = [x**2 for x in range(20) if x%2 == 0]
print(L)

[0, 4, 16, 36, 64, 100, 144, 196, 256, 324]
[0, 4, 16, 36, 64, 100, 144, 196, 256, 324]


In [48]:
# List comprehension using nested for loops
L1 = []
for x in range(5):
    for y in range(3):
        L1.append(x+y)
print(L1)

L = [x+y for x in range(5) for y in range(3)]
print(L)

[0, 1, 2, 1, 2, 3, 2, 3, 4, 3, 4, 5, 4, 5, 6]
[0, 1, 2, 1, 2, 3, 2, 3, 4, 3, 4, 5, 4, 5, 6]


In [49]:
# List comprehension for working with list of lists using nested for loops
L1 = []
for x in range(5):
    row = []
    for y in range(3):
        row.append(x+y)
    L1.append(row)

print(L1)

L = [[x+y for y in range(3)] for x in range(5)]

[[0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6]]


**Dictionary and Set Comprehensions**

Syntax for dictionary comprehension: `{key: value for element in iterable}`

Syntax for set comprehension: `{element for element in iterable}`

### 4. Lambda Functions

Python Lambda Functions are anonymous function meaning that the function exists without a name. As we already know, the `def` keyword is used to define a normal function in Python. Similarly, the `lambda` keyword is used to define an anonymous function in Python. 

The syntax would be: `val(optional) = lambda arguments: expression` 

In [102]:
# Python program to demonstrate
# lambda functions
 
x = "Avengers"
 
# lambda gets pass to print
output = lambda x: print(x)
output(x)

Avengers


Difference between `lambda` functions and `def` defined function

In [103]:
# Python code to illustrate cube of a number
# showing difference between def() and lambda()

def def_cube(y):
    return y*y*y # y**3
 
lambda_cube = lambda x: x**3
 
# using the normally defined function
print(def_cube(5))
 
# using the lambda function
print(lambda_cube(5))

125
125


As we can see in the above example both the `cube()` function and `lambda_cube()` function behave the same and as intended. Let’s analyze the above example a bit more:

**Without Lambda:** Here, both of them return the cube of a given number. But, while using `def`, we needed to define a function and needed to pass a value to it. After execution, we also needed to return the result from where the function was called using the `return` keyword.

**With Lambda:** Lambda definition does not include a `return` statement, it always contains an expression that is returned/printed. We can also put a `lambda` definition anywhere a function is expected, and we don’t have to assign it to a variable at all. This is the simplicity of `lambda` functions.

In [65]:
# Python code to illustrate lambda function
# with multiple parameters and default values

f1 = lambda x, y: x * y
f2 = lambda x, y, z = 0: x * y + z
f3 = lambda x, y, z = 0: f1(x, y) + z

print(f1(4, 6))
print(f2(4, 6))
print(f2(4, 6, 1))
print(f3(4, 6))
print(f3(4, 6, 1))

24
24
25
24
25


#### Lambda functions for Sorting

Lists in python can be sorted using `sorted()` based on some function of the elements present in them.

In [104]:
l = [("Mark", 1), ("Jack", 5), ("Jake", 7), ("Sam", 3)]
l = sorted(l, key = lambda x: -x[1])
# l = sorted(l)
print(l)

[('Jake', 7), ('Jack', 5), ('Sam', 3), ('Mark', 1)]


Sorting can be carried out at multiple hierarchical levels

In [69]:
l = [("Mark", 1), ("Jack", 4), ("Jake", 3), ("Sam", 2)]
l = sorted(l, key = lambda x: (-(x[1] % 2), -x[1])) # Sort by odd-even and then by descending order
print(l)

[('Jake', 3), ('Mark', 1), ('Jack', 4), ('Sam', 2)]


### 5. Functions and Scope

Python Functions are a block of related statements designed to perform a computational, logical, or evaluative task. The idea is to put some commonly or repeatedly done tasks together and make a function so that instead of writing the same code again and again for different inputs, we can do the function calls to reuse code contained in it over and over again. Functions can be both built-in or user-defined. It helps the program to be concise, non-repetitive, and organized.

In [ ]:
'''
def function_name(parameters(optional)):
    """docstring""" # optional
    statement(s)
    return expression # optional
'''

In [71]:
# A simple Python function
 
def welcome():
    print("Welcome to PIC 16A")
    # return None

a = welcome()
print(a)

welcome()

Welcome to PIC 16A
None
Welcome to PIC 16A


#### Global and local variables
**Global Variables**: In Python, a variable declared outside of the function or in global scope is known as a global variable

**Local Variables**: A variable declared inside the function's body or in the local scope is known as a local variable.

In [72]:
# Example 1: Create a Global Variable
x = "global"

def foo():
    print("x inside foo:", x)

foo()
print("x outside foo:", x)

x inside foo: global
x outside foo: global


In the above code, we created `x` as a global variable and defined a `foo()` to print the global variable `x`. Finally, we call the `foo()` which will print the value of `x`. What if we want to change the value of `x` inside a function?

In [74]:
# inside a function: it will look for the variable in the local scope, if not found, it will look for the variable in the 
# global scope or look for a default value
# and if that is also not found, it will raise an error or use inbuilt namescope
x = "global"

def foo():
    x = 3
    x = x * 2
    print(x)

foo()
print(x)

6
global


Here, we will see how global variables and local variables can be used in the same code.

In [76]:
# Example: Using Global and Local variables in the same code
x = "global "

def foo():
    global x
    y = "local"
    x = x * 2
    print("x Inside foo:",x)
    print("y Inside foo:",y)

foo()
print("x Outside foo:",x)
#print("y Outside foo:",y) # This will cause a NameError: name 'y' is not defined

x Inside foo: global global 
y Inside foo: local
x Outside foo: global global 


In the above code, we declare `x` as a "global" and `y` as a local variable with value "local" in the `foo()`. Then, we use multiplication operator `*` to modify the global variable `x` and we print both `x` and `y`.

After calling the `foo()`, the value of `x` becomes "global global" because we used the `x * 2` to print two times global. After that, we print the value of local variable `y` i.e local.

In [78]:
# Example: Global variable and Local variable with same name
 
x = 5
print("global x:", x)
def foo():
    x = 10
    print("local x:", x)

foo()
print("global x:", x)

global x: 5
local x: 10
global x: 5


### 6. Numpy Broadcasting

Briefly discuss Boolean Indexing in Numpy.

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array. For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [3]:
import numpy as np

In [4]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])

# Create an empty matrix with the same shape as x
y = np.empty_like(x)   

# Add the vector v to each row of the matrix x with an explicit for loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this:

In [5]:
# Stack 4 copies of v on top of each other
# Prints "[[1 0 1]
#          [1 0 1]
#          [1 0 1]
#          [1 0 1]]"
vv = np.tile(v, (4, 1))
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [6]:
# Add x and vv elementwise
y = x + vv
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [7]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])

# Add v to each row of x using broadcasting
y = x + v  
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Broadcasting rules:

1. If the arrays have different number of dimensions, prepend the shape of the lower dimensional array with 1s until both have same number of dimensions.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

If this explanation does not make sense, try reading the explanation from the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or this [explanation](http://wiki.scipy.org/EricsBroadcastingDoc).

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are some applications of broadcasting:

In [8]:
# Compute outer product of vectors
v = np.array([1, 2, 3])  # v has shape (3,)
w = np.array([4, 5])     # w has shape (2,)

# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
print(v.reshape(3, 1) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [11]:
# Add a vector to each row of a matrix
x = np.array([[1, 2, 3], 
              [4, 5, 6]])
v = np.array([1, 2, 3])

# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x<=2)

[[ True  True False]
 [False False False]]


In [86]:
x = np.array([[1, 2, 3], [4, 5, 6]])
w = np.array([4, 5])

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,)
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
print((x.T + w).T) # .T can be used to get the transpose

[[ 5  6  7]
 [ 9 10 11]]


In [87]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same output.
print(x + w.reshape(2, 1))

[[ 5  6  7]
 [ 9 10 11]]


In [88]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible. This brief overview has touched on many of the important things that you need to know about numpy broadcasting, but is far from complete. Please check out the documentation of any numpy functions you come across to know more about it!

### 7. Iterators and Generators

In [41]:
# Example for Iterators and Generators
# A class to iterate over a dictionary's elements sorted by the keys
class ABC:
    def __init__(self, frequency):
        self.f = frequency
    def __iter__(self):
        # What will you do here?
        return ABC_Iterator(self)

class ABC_Iterator:
    def __init__(self, x):
        self.freq = x.f
        self.order = list(self.freq.keys())
        self.order.sort()
        self.count = 0

    def __next__(self):
        # What will you do here?
        if self.count>=len(self.freq):
            raise StopIteration
        self.count+=1
        return (self.order[self.count-1],self.freq[self.order[self.count-1]])
        
def ABC_Generator(x):
    order = list(x.f.keys())
    order.sort()
    # What will you do here?
    for i in range(len(x.f)):
        yield (order[i],x.f[order[i]])

def ABC_Generator_vals(x):
    order = list(x.f.items())
    order = sorted(order, key = lambda x: x[1])
    # What will you do here?
    for i in range(len(x.f)):
        yield (order[i])

In [42]:
occurences = {'G':32, 'O':12, 'A':25, 'T':10}

abc = ABC(occurences)
# The purpose of this is to sequentially print the keys and values of the dictionary sorted by the keys
for i in abc:
    print(i)

('A', 25)
('G', 32)
('O', 12)
('T', 10)


In [43]:
for i in ABC_Generator(abc):
    print(i)

('A', 25)
('G', 32)
('O', 12)
('T', 10)


In [44]:
for i in ABC_Generator_vals(abc):
    print(i)

('T', 10)
('O', 12)
('A', 25)
('G', 32)
